  image: node:22.13
  stages:
    - build
    - deploy

  cache:
    paths:
      - node_modules/

  build:
    stage: build
    script:
      - npm install
      - npm run build
    artifacts:
      paths:
        - .output/public
      expire_in: 30 days
    rules:
      - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
        when: manual

  deploy:
    stage: deploy
    script:
      - >
        curl -X POST
        -H "Authorization: Bearer $AZURE_STATIC_WEB_APPS_TOKEN"
        -d '{}'
        "$AZURE_DEPLOY_HOOK_URL"
    rules:
      - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
        when: on_success
    needs:
      - build # only deploy if build succeeds

  rollback:
    stage: deploy
    script:
      - echo "Rolling back to previous successful build..."
      - >
        curl -X POST
        -H "Authorization: Bearer $AZURE_STATIC_WEB_APPS_TOKEN"
        -d '{}' 
        "$AZURE_DEPLOY_HOOK_URL"
    rules:
      - if: '$CI_COMMIT_BRANCH == "main"'
        when: manual
    dependencies:
      - build
