  image: node:22.13-alpine3.20
  stages:
    - build
    - deploy

  cache:
    paths:
      - node_modules/

  validate:
    stage: build
    script:
      - echo "No tests yet - placeholder for future CI events"
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME == "main"'

  build:
    stage: build
    script:
      - npm install
      - npm run build
    artifacts:
      paths:
        - .output/public
      expire_in: 30 days
    rules:
      - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
        when: manual
    needs:
      - validate # build will only run if validate succeeds

  deploy:
    stage: deploy
    script:
      - >
        curl -X POST
        -H "Authorization: Bearer $AZURE_STATIC_WEB_APPS_TOKEN"
        -d '{}'
        "$AZURE_DEPLOY_HOOK_URL"
    rules:
      - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
        when: manual
    needs:
      - build # only deploy if build succeeds

  rollback:
    stage: deploy
    script:
      - echo "Rolling back to previous successful build..."
      - >
        curl -X POST
        -H "Authorization: Bearer $AZURE_STATIC_WEB_APPS_TOKEN"
        -d '{}' 
        "$AZURE_DEPLOY_HOOK_URL"
    rules:
      - if: '$CI_COMMIT_BRANCH == "main"'
        when: manual
    dependencies:
      - build
